name: SEGFAULT

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '*/20 * * * *' # Restart every 20 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Connect to SSH and run command
        env:
          SECRET: ${{ secrets.SECRET }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o "SetEnv SECRET=${{ secrets.SECRET }}" -o "StrictHostKeyChecking=no" root@${{ secrets.SSH_HOST }} " cd /sec/root/cconk/js_osr || { echo 'Failed to change to /sec/root/cconk/js_osr'; exit 1; } && python3 rieng.py || { echo 'Python script execution failed'; exit 1; } "
